bootstrap: Fix TLS, check if .entware exists, and improve error messages
This PR contains several fixes for the bootstrap script.

* If the standalone `wget` binary cannot be fetched, a more helpful error message is printed instead of the catch-all error message (see #422).
* The standalone `wget` binary is fetched over HTTP instead of HTTPS, since the implementation of TLS in Busybox’s wget causes issues with the latest version of nginx. This does not reduce security since the checksum is still verified after fetching the binary (fixes #422, I believe).
* Abort installation if `/home/root/.entware` already exists. Previously, only the existence of `/opt` was checked, leading to #409.

Test plan (on rM1 and rM2):

* Try to run the script normally. Issue #422 should be fixed and the install should proceed.
* Try to run the script while not being connected to Wi-Fi. Expected output:

```sh
INFO:  Fetching secure wget
wget: bad address 'toltec-dev.org'
ERROR: Could not fetch wget, make sure you have a stable Wi-Fi connection
```

* Try to run it with `127.0.0.1 toltec-dev.org` in `/etc/hosts`. Expected output:

```sh
INFO:  Fetching secure wget
wget: can't connect to remote host (127.0.0.1): Connection refused
ERROR: Could not fetch wget, make sure you have a stable Wi-Fi connection
```

* Starting from a complete Toltec install, unmount /opt (`systemctl stop opt.mount`) and remove the /opt folder. Try to run the script. Expected output:

```sh
INFO:  Toltec is already installed or partially installed
INFO:  To re-enable Toltec after a system upgrade, run 'toltecctl reenable'
INFO:  To reinstall Toltec, run 'toltecctl uninstall' first
```